frase = 'Curso em Video Python'
print(frase[1:15])
print(frase[1:15:2])
print(frase[::2])
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(len(frase.strip()))
print(frase.replace('Python','Android'))
print(frase.find('Video'))
print(frase.lower().find('video'))
print(frase.split())
dividido = frase.split()
print(dividido[2][3])